

### Iniciar sesión como usuario con rol "admin"
POST http://localhost:4000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "123456"
}

# Copia el token recibido en la respuesta (se usará como <tu-token>)

###
###
###
### Listar todos los médicos activos
GET http://localhost:4000/api/v1/medicos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNTQ4NDYyLCJleHAiOjE3NDE5MDg0NjJ9.72B3i4ECmxq-lD4mnM3ZU_kaXgzpInXRGas7JAUS6EE

### Listar todas las fichas médicas activas
GET http://localhost:4000/api/v1/fichasmedicas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNTQ4NDYyLCJleHAiOjE3NDE5MDg0NjJ9.72B3i4ECmxq-lD4mnM3ZU_kaXgzpInXRGas7JAUS6EE


### Crear una ficha médica        "_id": "67ce2fa2c935385375940131",
POST http://localhost:4000/api/v1/fichasmedicas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNTQ4NDYyLCJleHAiOjE3NDE5MDg0NjJ9.72B3i4ECmxq-lD4mnM3ZU_kaXgzpInXRGas7JAUS6EE


{
  "paciente": "67ca23c779e062bd415db73f",
  "medico": "67ca2cf74cab82850ee4639e",
  "especialidad": "67ca2a0c4cab82850ee4637b",
  "diagnostico": "Dolor abdominal inicial"
}

# Respuesta esperada: 201 Created con la ficha (copia el _id)67cdf3d46821cc67d3a71049

###
###
### Crear una consulta médica    medico activo o true 67ce3011c93538537594013d
POST http://localhost:4000/api/v1/consultasmedicas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNTQ4NDYyLCJleHAiOjE3NDE5MDg0NjJ9.72B3i4ECmxq-lD4mnM3ZU_kaXgzpInXRGas7JAUS6EE

{
"paciente": "67ca23c779e062bd415db73f",
  "medico": "67c783c543449cb8ad3460d1",
  "fichaMedica": "67ce2fa2c935385375940131",
  "especialidad": "67c7801b46481074013e0210",
  "fecha": "2025-03-09T10:00:00Z",
  "motivo": "Dolor abdominal",
  "observaciones": "Paciente refiere dolor desde hace 2 días",
  "prioridad": "Alta",
  "duracion": 45
}

### listar todas las consultas medicas
GET http://localhost:4000/api/v1/consultasmedicas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNTQ4NDYyLCJleHAiOjE3NDE5MDg0NjJ9.72B3i4ECmxq-lD4mnM3ZU_kaXgzpInXRGas7JAUS6EE

# Respuesta esperada: 200 OK con la lista de consultas médicas

###

# Obtener una consulta médica por ID 67ce3011c93538537594013d
GET http://localhost:4000/api/v1/consultasmedicas/67ce3011c93538537594013d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

# Respuesta esperada: 200 OK con los detalles de la consulta

###

# Listar consultas médicas por paciente 67cba12fa78ad406e838da79
GET http://localhost:4000/api/v1/consultasmedicas/paciente/67ca23c779e062bd415db73f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

# Respuesta esperada: 200 OK con la lista de consultas del paciente

###

# Actualizar una consulta médica
PUT http://localhost:4000/api/v1/consultasmedicas/67ce3011c93538537594013d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

{

"observaciones": "Paciente mejoró tras analgésicos"

}

# Respuesta esperada: 200 OK con la consulta actualizada

###

# Concluir una consulta médica
PATCH http://localhost:4000/api/v1/consultasmedicas/conclude/67ce3011c93538537594013d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

# Respuesta esperada: 200 OK con la consulta marcada como "Concluida"

###

# Derivar una consulta médica a otro médico 67ca2ad74cab82850ee46383
PATCH http://localhost:4000/api/v1/consultasmedicas/derive/67ce3011c93538537594013d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

{
  "medico": "67ca2ad74cab82850ee46383"
}

# Respuesta esperada: 200 OK con la consulta marcada como "Derivada" y medicoDerivado asignado

###

# Reasignar una consulta médica a otro médico ide de consulta Id 67c783c543449cb8ad3460d1
PATCH http://localhost:4000/api/v1/consultasmedicas/reassign/67ce3011c93538537594013d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

{
  "medico": "67c8e996f086f15dea74aae7"
}

# Respuesta esperada: 200 OK con el médico reasignado y estadoConsulta como "Pendiente"


###

# Eliminar Lógicamente una Consulta Médica (Soft Delete) de consulta Id 67ce3011c93538537594013d
PATCH http://localhost:4000/api/v1/consultasMedicas/softDelete/67ce3011c93538537594013d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg


###

# Eliminar Físicamente una Consulta Médica Id 67ce3011c93538537594013d
DELETE http://localhost:4000/api/v1/consultasMedicas/67ce3011c93538537594013d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg





###

# Programar una Cita (/citas)
POST http://localhost:4000/api/v1/citas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

{
  "paciente": "67cba12fa78ad406e838da79",
  "medico": "67c783c543449cb8ad3460d1",
  "fichaMedica": "67c784c543449cb8ad3460d2",
  "especialidad": "67c7801b46481074013e0210",
  "fecha": "2025-03-08T14:00:00Z",
  "motivo": "Revisión de rutina",
  "observaciones": "Paciente solicita chequeo general",
  "prioridad": "Normal",
  "duracion": 30
}

# Respuesta esperada: 200 OK con confirmación de eliminación

###
# 2. Listar Citas Programadas
GET http://localhost:4000/api/v1/citas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg



###

# Actualizar una Cita
PUT http://localhost:4000/api/v1/citas/67ce2a18351647cd9a81b2b9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

{
  "fecha": "2025-03-08T15:00:00Z",
  "duracion": 45,
  "observaciones": "Paciente cambió horario"
}

# Respuesta esperada: 200 OK con confirmación de eliminación

###

# Cancelar una Cita
DELETE http://localhost:4000/api/v1/citas/67ce2a18351647cd9a81b2b9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

{

"fecha": "2025-03-08T15:00:00Z",
  "duracion": 45,
  "observaciones": "Paciente cambió horario"
}

###


