# Crear una nueva relación paciente-obstétrico/ginecológico
POST http://localhost:4000/api/v1/paciente-obstetricos-ginecologicos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNjM5NzQ3LCJleHAiOjE3NDE5OTk3NDd9.iuXR8_sAZg42UR4C5D0REdH99CChqwa1N6YNfiB5ubY

{
  "paciente": "67c1404975156d4ce24ca2e4", 
  "tipoObstetricoGinecologico": "67c14fd92f65123b7fa7d2fd",  
  "fechaEvento": "2025-02-25",
  "embarazos": 2,
  "partos": 2,
  "abortos": 0,
  "cesareas": 0,
  "menarca": "12",
  "cicloMenstrual": "Regular",
  "observaciones": "Control prenatal de rutina"
}

###
# Listar todas las relaciones paciente-obstétrico/ginecológico
GET http://localhost:4000/api/v1/paciente-obstetricos-ginecologicos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNjM5NzQ3LCJleHAiOjE3NDE5OTk3NDd9.iuXR8_sAZg42UR4C5D0REdH99CChqwa1N6YNfiB5ubY

###
# Obtener una relación paciente-obstétrico/ginecológico por ID
GET http://localhost:4000/api/v1/paciente-obstetricos-ginecologicos/67ca76fdf849bb0a2c45ea6c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNjM5NzQ3LCJleHAiOjE3NDE5OTk3NDd9.iuXR8_sAZg42UR4C5D0REdH99CChqwa1N6YNfiB5ubY

###
# Actualizar una relación paciente-obstétrico/ginecológico
PUT http://localhost:4000/api/v1/paciente-obstetricos-ginecologicos/67ca76fdf849bb0a2c45ea6c HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNjM5NzQ3LCJleHAiOjE3NDE5OTk3NDd9.iuXR8_sAZg42UR4C5D0REdH99CChqwa1N6YNfiB5ubY

{
  "descripcion": "Control prenatal conreyretyrtertyerytery resultados normales"
}

###
# Eliminar lógicamente una relación paciente-obstétrico/ginecológico (cambiar a Inactivo)
PATCH http://localhost:4000/api/v1/paciente-obstetricos-ginecologicos/67bc14f2906952918cabf625/soft-delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNjM5NzQ3LCJleHAiOjE3NDE5OTk3NDd9.iuXR8_sAZg42UR4C5D0REdH99CChqwa1N6YNfiB5ubY

###
# Eliminar físicamente una relación paciente-obstétrico/ginecológico (si aplica, aunque prefieres eliminaciones lógicas)
DELETE http://localhost:4000/api/v1/paciente-obstetricos-ginecologicos/67bc14f2906952918cabf625 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNjM5NzQ3LCJleHAiOjE3NDE5OTk3NDd9.iuXR8_sAZg42UR4C5D0REdH99CChqwa1N6YNfiB5ubY