# Crear una nueva ficha médica
POST http://localhost:4000/api/v1/fichas-medicas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNzIxNTg1LCJleHAiOjE3NDEwODE1ODV9.X3b3zSiszSInn2QkVkh2_xjoh19aez5m-8S-WCIcix4

{
  "medico": "67c1404975156d4ce24ca2e4",  
  "paciente": "67c1480aff8a064058786d3d",  
  "fecha": "2025-02-25",
  "diagnostico": "Paciente presenta hipertensión leve"
}

###
# Listar todas las fichas médicas
GET http://localhost:4000/api/v1/fichas-medicas HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNzIxNTg1LCJleHAiOjE3NDEwODE1ODV9.X3b3zSiszSInn2QkVkh2_xjoh19aez5m-8S-WCIcix4

###
# Obtener una ficha médica por ID
GET http://localhost:4000/api/v1/fichas-medicas/67c16f14efceb12b75fe87a5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNzIxNTg1LCJleHAiOjE3NDEwODE1ODV9.X3b3zSiszSInn2QkVkh2_xjoh19aez5m-8S-WCIcix4

###
# Actualizar una ficha médica
PUT http://localhost:4000/api/v1/fichas-medicas/67009a72d4d2db15547140a1 HTTP/1.1
  "medico": "67c1404975156d4ce24ca2e4",  
  "paciente": "67c1480aff8a064058786d3d" 

{
  "diagnostico": "Paciente presenta hipertensión leve controlada con medicación",
  "fecha": "2025-02-26"
}

###
# Eliminar lógicamente una ficha médica (cambiar a Inactivo)
PATCH http://localhost:4000/api/v1/fichas-medicas/67bc14f2906952918cabf625/soft-delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNzIxNTg1LCJleHAiOjE3NDEwODE1ODV9.X3b3zSiszSInn2QkVkh2_xjoh19aez5m-8S-WCIcix4

###
# Eliminar físicamente una ficha médica (si aplica, aunque prefieres eliminaciones lógicas)
DELETE http://localhost:4000/api/v1/fichas-medicas/67bc14f2906952918cabf625 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNzIxNTg1LCJleHAiOjE3NDEwODE1ODV9.X3b3zSiszSInn2QkVkh2_xjoh19aez5m-8S-WCIcix4