# Crear un nuevo médico
POST http://localhost:4000/api/v1/medicos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YmMxNTEzOTA2OTUyOTE4Y2FiZjYyOCIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNTMwNTMzLCJleHAiOjE3NDA1MzQxMzN9.cgeyW8BN2dQ1Dz_4_0l2VhZq7EOepCCcLplnMogjS2Y

{
  "primerNombre": "María",
  "segundoNombre": "Isabel",
  "primerApellido": "Gómez",
  "segundoApellido": "López",
  "fechaNacimiento": "1985-03-20",
  "lugarNacimiento": "Quito",
  "nacionalidad": "Ecuatoriana",
  "ciudadDondeVive": "Guayaquil",
  "direccion": "Calle 789, Barrio Central",
  "telefono": "987654323",
  "celular": "0987654323",
  "genero": "Femenino",
  "cedula": "1234567891"
}

###
# Listar todos los médicos
GET http://localhost:4000/api/v1/medicos HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YmMxNTEzOTA2OTUyOTE4Y2FiZjYyOCIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNTMwNTMzLCJleHAiOjE3NDA1MzQxMzN9.cgeyW8BN2dQ1Dz_4_0l2VhZq7EOepCCcLplnMogjS2Y

###
# Obtener un médico por ID
GET http://localhost:4000/api/v1/medicos/67bc130a7d9eab592d2d02cf HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YmMxNTEzOTA2OTUyOTE4Y2FiZjYyOCIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNTMwNTMzLCJleHAiOjE3NDA1MzQxMzN9.cgeyW8BN2dQ1Dz_4_0l2VhZq7EOepCCcLplnMogjS2YA

###
# Actualizar un médico
PUT http://localhost:4000/api/v1/medicos/67009a72d4d2db15547140a1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YmMxNTEzOTA2OTUyOTE4Y2FiZjYyOCIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNTMwNTMzLCJleHAiOjE3NDA1MzQxMzN9.cgeyW8BN2dQ1Dz_4_0l2VhZq7EOepCCcLplnMogjS2Y

{
  "direccion": "Avenida 101, Nueva Zona",
  "telefono": "987654324"
}

###
# Eliminar lógicamente un médico (cambiar a Inactivo)
PATCH http://localhost:4000/api/v1/medicos/67bc14f2906952918cabf625/soft-delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YmMxNTEzOTA2OTUyOTE4Y2FiZjYyOCIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNTMwNTMzLCJleHAiOjE3NDA1MzQxMzN9.cgeyW8BN2dQ1Dz_4_0l2VhZq7EOepCCcLplnMogjS2Y

###
# Eliminar físicamente un médico (si aplica, aunque en tu sistema prefieres eliminaciones lógicas)
DELETE http://localhost:4000/api/v1/medicos/67bc14f2906952918cabf625 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YmMxNTEzOTA2OTUyOTE4Y2FiZjYyOCIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNTMwNTMzLCJleHAiOjE3NDA1MzQxMzN9.cgeyW8BN2dQ1Dz_4_0l2VhZq7EOepCCcLplnMogjS2Y