# Crear un nuevo paciente
POST http://localhost:4000/api/v1/pacientes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNTcxNzYxLCJleHAiOjE3NDE5MzE3NjF9.UV28hx1dx6a4I2r_lz3qqoe-XouIrhf35VxcpvGEvbk

 {
    "cedula": "5678901774",
    "primerNombre": "Luigdgdsfgs",
    "segundoNombre": "Midgdfsfgsdguel",
    "primerApellido": "Sánsdgfdfchez",
    "segundoApellido": "Mosdfgsdrales",
    "fechaNacimiento": "1990-09-12T00:00:00.000+00:00",
    "direccion": "Calle 20, Zona Norte",
    "telefono": "915678901",
    "celular": "0954321098",
    "genero": "Masculino"

}

###
# Listar todos los pacientes
GET http://localhost:4000/api/v1/pacientes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxODE4NjA5LCJleHAiOjE3NDIxNzg2MDl9.pwq5m4piwpvEkFDXaUM7ldaKf6ZGrNgk9FmVXXpWKJc

###
# Obtener un paciente por ID
GET http://localhost:4000/api/v1/pacientes/67ca23a879e062bd415db737 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNTcxNzYxLCJleHAiOjE3NDE5MzE3NjF9.UV28hx1dx6a4I2r_lz3qqoe-XouIrhf35VxcpvGEvbk

###
# Actualizar un paciente
PUT http://localhost:4000/api/v1/pacientes/67ca23a879e062bd415db737 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNTcxNzYxLCJleHAiOjE3NDE5MzE3NjF9.UV28hx1dx6a4I2r_lz3qqoe-XouIrhf35VxcpvGEvbk

{
  "direccion": "456 456, Nueva Ciudad ",
  "telefono": "1111111111"
}

###
# Eliminar lógicamente un Paciente cambiado a estado Inactivo (cambiar a Inactivo)
PATCH http://localhost:4000/api/v1/pacientes/67ca23a879e062bd415db737/soft-delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNTcxNzYxLCJleHAiOjE3NDE5MzE3NjF9.UV28hx1dx6a4I2r_lz3qqoe-XouIrhf35VxcpvGEvbk
###
# Eliminar físicamente un paciente (si aplica, aunque en tu sistema prefieres eliminaciones lógicas)
DELETE http://localhost:4000/api/v1/pacientes/67bc14f2906952918cabf625 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxNTcxNzYxLCJleHAiOjE3NDE5MzE3NjF9.UV28hx1dx6a4I2r_lz3qqoe-XouIrhf35VxcpvGEvbk