# Crear un nuevo paciente
POST http://localhost:4000/api/v1/pacientes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

 {
    "cedula": "5678901234",
    "primerNombre": "Luis",
    "segundoNombre": "Miguel",
    "primerApellido": "Sánchez",
    "segundoApellido": "Morales",
    "fechaNacimiento": "1990-09-12T00:00:00.000+00:00",
    "direccion": "Calle 20, Zona Norte",
    "telefono": "915678901",
    "celular": "0954321098",
    "genero": "Masculino"

}

###
# Listar todos los pacientes
GET http://localhost:4000/api/v1/pacientes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg
###
# Obtener un paciente por ID
GET http://localhost:4000/api/v1/pacientes/67ca2290d33c16ae9d3e532e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

###
# Actualizar un paciente
PUT http://localhost:4000/api/v1/pacientes/67ca2290d33c16ae9d3e532e HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg
{
  "direccion": "456 456, Nueva Ciudad",
  "telefono": "1111111111"
}

###
# Eliminar lógicamente un Paciente cambiado a estado Inactivo (cambiar a Inactivo)
PATCH http://localhost:4000/api/v1/pacientes/67ca2290d33c16ae9d3e532e/soft-delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg
###
# Eliminar físicamente un paciente (si aplica, aunque en tu sistema prefieres eliminaciones lógicas)
DELETE http://localhost:4000/api/v1/pacientes/67bc14f2906952918cabf625 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg