# Crear un nuevo rol

POST http://localhost:4000/api/v1/roles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg


# {
#   "name": "user",
#   "permissions": ["posts_read", "posts_write","posts_update", "posts_delete"]
# }
# {
#   "name": "admin",
#   "permissions": ["admin_granted"]
# }
# {
#   "name": "manager",
#   "permissions": ["posts_read", "posts_write","posts_update", "posts_delete", "users_read", "users_write","users_update"]
# }
{"name": "Fichaje","permissions": ["admin_granted"]}
### listar los roles
GET http://localhost:4000/api/v1/roles HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

###
GET http://localhost:4000/api/v1/roles/67c00584f66f819a4ccccb2d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg
### actualizar por id
PUT http://localhost:4000/api/v1/roles/67c00584f66f819a4ccccb2d HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg

{
    "permissions": [
       "users_read",
          "users_write",
          "users_update",
          "users_delete",
          "roles_read",
          "roles_write",
          "roles_update",
          "roles_delete",
          "pacientes_read",
          "pacientes_write",
          "pacientes_update",
          "pacientes_delete",
          "pacientes_soft-delete",
          "medicos_read",
          "medicos_write",
          "medicos_update",
          "medicos_delete",
          "medicos_delete",
          "tiposadicciones_read",
          "tiposadicciones_write",
          "tiposadicciones_update",
          "tiposadicciones_delete",
          "tiposadicciones_soft-delete",
          "tiposobstetricosginecologicos_read",
          "tiposobstetricosginecologicos_write",
          "tiposobstetricosginecologicos_update",
          "tiposobstetricosginecologicos_delete",
          "tiposobstetricosginecologicos_soft-delete",
          "tiposoperacionesquirurgicas_read",
          "tiposoperacionesquirurgicas_write",
          "tiposoperacionesquirurgicas_update",
          "tiposoperacionesquirurgicas_delete",
          "tiposoperacionesquirurgicas_soft-delete",
          "examenesmedicos_read",
          "examenesmedicos_write",
          "examenesmedicos_update",
          "examenesmedicos_delete",
          "examenesmedicos_soft-delete",
          "fichasmedicas_read",
          "fichasmedicas_write",
          "fichasmedicas_update",
          "fichasmedicas_delete",
          "fichasmedicas_soft-delete",
          "consultasmedicas_read",
          "consultasmedicas_write",
          "consultasmedicas_update",
          "consultasmedicas_delete",
          "consultasmedicas_soft-delete",
          "recetasmedicas_read",
          "recetasmedicas_write",
          "recetasmedicas_update",
          "recetasmedicas_delete",
          "recetasmedicas_soft-delete",
          "medicamentos_read",
          "medicamentos_write",
          "medicamentos_update",
          "medicamentos_delete",
          "pacienteadicciones_read",
          "pacienteadicciones_write",
          "pacienteadicciones_update",
          "pacienteadicciones_delete",
          "pacienteobstetricosginecologicos_read",
          "pacienteobstetricosginecologicos_write",
          "pacienteobstetricosginecologicos_update",
          "pacienteobstetricosginecologicos_delete",
          "pacienteoperaciones_read",
          "pacienteoperaciones_write",
          "pacienteoperaciones_update",
          "pacienteoperaciones_delete",
          "recetasmedicamentos_read",
          "recetasmedicamentos_write",
          "recetasmedicamentos_update",
          "recetasmedicamentos_delete",
          "pacienteexamenes_read",
          "pacienteexamenes_write",
          "pacienteexamenes_update",
          "pacienteexamenes_delete",
          "especialidades_read",
          "especialidades_write",
          "especialidades_update",
          "especialidades_delete",
          "administrativos_read",
          "administrativos_write",
          "administrativos_update",
          "administrativos_delete",
          "admin_granted"
    ]
}



### eliminar un rol
DELETE http://localhost:4000/api/v1/roles/67c0cd5269a80b6efa082021 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA4MzgxOTdjN2VhYzQzYmEzNzM3ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQxMjMyMTk0LCJleHAiOjE3NDE1OTIxOTR9.5J7t6VVfam98n0XYkn9je0s4MX-SO4TleHgCkg2pgtg