# Crear un nuevo usuario
POST http://localhost:4000/api/v1/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA3ZDdhODRmNTFkMzAwNzdhYTA5OSIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNjY4NjAxLCJleHAiOjE3NDA2NzIyMDF9.qJI-Ze9wTb6aJessJ70c8EEmDzO0_DwK-ZRcYpDm0sg

{
  "name": "Ana López",
  "username": "alopez",
  "email": "alopez@clinica.com",
  "password": "securepassword123",
  "roles": "manager"
}

###
# Listar todos los usuarios activos
GET http://localhost:4000/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzA3ZDdhODRmNTFkMzAwNzdhYTA5OSIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNjY4Mjk0LCJleHAiOjE3NDA2NzE4OTR9.cRUl_9MuHWMsXvW7WF_prEQnx3lvz323mz5JGl1w4pw
###
# Obtener un usuario por ID
GET http://localhost:4000/api/v1/users/67c00caefd81d387f05e8e62 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzAwZDk1ZmQ4MWQzODdmMDVlOGU2ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNjY4MDM0LCJleHAiOjE3NDA2NzE2MzR9.otgr6TLLHmYxNDznj_G5ieRe9QHPlWpfTY66hsxuMZM

###
# Actualizar un usuario
PUT http://localhost:4000/api/v1/users/67c00caefd81d387f05e8e62 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzAwZDk1ZmQ4MWQzODdmMDVlOGU2ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNjY4MDM0LCJleHAiOjE3NDA2NzE2MzR9.otgr6TLLHmYxNDznj_G5ieRe9QHPlWpfTY66hsxuMZM

{
  "name": "Ana María López",
  "email": "amlopez@clinica.com"
}

###
# Eliminar lógicamente un usuario (cambiar a Inactivo)
PATCH http://localhost:4000/api/v1/users/67bc14f2906952918cabf625/soft-delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzAwZDk1ZmQ4MWQzODdmMDVlOGU2ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNjY4MDM0LCJleHAiOjE3NDA2NzE2MzR9.otgr6TLLHmYxNDznj_G5ieRe9QHPlWpfTY66hsxuMZM

###
# Eliminar físicamente un usuario
DELETE http://localhost:4000/api/v1/users/67bc14f2906952918cabf625 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YzAwZDk1ZmQ4MWQzODdmMDVlOGU2ZiIsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzQwNjY4MDM0LCJleHAiOjE3NDA2NzE2MzR9.otgr6TLLHmYxNDznj_G5ieRe9QHPlWpfTY66hsxuMZM